config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end


  resources :posts do
    resources :comments
  end

  root "posts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, :dependent => :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_post
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]


  # GET /comments or /comments.json
  def index
    @comments = @post.comments
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
    current_user.comments << @comment
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    current_user.comments << @comment

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_url(@post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_url(@post), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_url(@post), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def correct_user
    redirect_to post_path(@comment.post), notice: "Unauthorized action!" if @comment.user_id != current_user.id
  end
  private
    def get_post
      @post = Post.find(params[:post_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:name, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    #@post = Post.new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to post_path, notice: "Unauthorized action!" if @post.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" >
  <p>
    <strong><%= comment.user.username %></strong>

  </p>

  <p>

    <%= comment.body %>
  </p>


  <div class="row">
  <div class="col">
    <%= link_to "Edit this comment", edit_post_comment_path(comment.post, comment) , class:"col btn btn-secondary " %>
  </div>

    <div class="col">
    <%= button_to "Destroy this comment", [comment.post, comment], method: :delete , class:"col btn btn-danger" %>
  </div>
  </div>

</div>
<hr/>

app/views/comments/_edit_form.html.erb
<%= form_with(model: [@post, comment]) do |form|  %>
  <%if !comment.nil?%>
 <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%end%>


  <div>
    <%= form.text_area :body ,class: "form-control"%>
  </div>

  <div>
    <%= form.submit  class: "btn btn-primary my-3"%>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @post.comments.build]) do |form| %>
  <%if !comment.nil?%>
 <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%end%>


  <div>
    <%= form.label "Comment", style: "display: block" , class: "form-label"%>
    <%= form.text_area :body , class: "form-control"%>
  </div>

  <div>
    <%= form.submit  class: "btn btn-primary my-3"%>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "edit_form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to Post", post_path(@comment.post) ,class: "btn btn-secondary"%>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <%= link_to "Show Post",post_path(comment.post) ,class: "btn btn-secondary"%>
  <% end %>
</div>

<%= link_to "New comment", new_post_comment_path ,class: "btn btn-primary"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <style>
        body {
          background-image: url('https://unsplash.com/photos/EPdt8UIIqK8/download?ixid=MnwxMjA3fDB8MXx0b3BpY3x8Ym84alFLVGFFMFl8fHx8fDJ8fDE2NTgzNDU3NDA&force=true&w=2400');
          background-size: cover;
          background-color: rgba(0,0,0, 0.9);
          background-blend-mode: multiply;
        }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>

  </head>

  <body >
    <%= render 'posts/navbar'%>
    <div class="container fluid my-3">
    <% if !notice.nil? %>
      <div class="alert alert-primary rounded-5 px-5" role="alert">
        <%= notice%>
      </div>
    <%end%>
    <% if !alert.nil? %>
      <div class="alert alert-primary rounded-5 px-5" role="alert">
        <%= alert%>
      </div>
    <%end%>
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class = "bg-light rounded-5 m-5 p-5">

  <div>
    <%= form.label :title, style: "display: block" ,class:"form-label"%>
    <%= form.text_field :title ,class:"form-control"%>
  </div>

  <div>
    <%= form.label :body, style: "display: block",class:"form-label" %>
    <%= form.text_area :body ,class:"form-control"%>
  </div>

  <div >
    <%= form.submit class:"btn btn-primary my-3"%>
  </div>
  </div>
<% end %>

app/views/posts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Blog", root_path , class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li>
        <%= link_to "Posts", posts_path, class: "navbar-item nav-link"%>
        </li>

      <%if user_signed_in?%>
        <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
         <li>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "navbar-item nav-link" %>
        </li>
      <%else%>
        <li>
        <%= link_to "Log in", new_user_session_path, class: "navbar-item nav-link"%>
        </li>
         <li>
        <%= link_to "Sign Up", new_user_registration_path, class: "navbar-item nav-link"%>
        </li>

      <%end%>
    </ul>
    </div>
  </div>
</nav>

app/views/posts/_post.html.erb
<div class="table" id="<%= dom_id post %>">
  <h1>

    <%= post.title %>
  </h1>

  <div>
    by <strong> <%= post.user.username %></strong>
  </div>


</div>

<p><%= post.body %></p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div class="row mx-5">
<div class="col">
  <%= link_to "Show this post", @post ,class: "btn btn-secondary" %>
  </div>
<div class="col">

  <%= link_to "Back to posts", posts_path ,class: "btn btn-secondary"%>
  </div>

</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div id="posts" class="container my-5 p-5 bg-light rounded-5">
  <%= @posts.count.to_s + " post(s)"%>
  <hr/>
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post ,class: "btn btn-secondary"%>
    </p>
    <hr/>
  <% end %>
</div>

<%= link_to "New post", new_post_path ,class: "btn btn-primary"%>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path ,class: "btn btn-secondary mx-5"%>
</div>

app/views/posts/show.html.erb
<div class="bg-light rounded-5 m-5 p-5">
  <%= render @post %>

  <div class="row">
    <div class="col">
      <%= link_to "Edit this post", edit_post_path(@post) ,class: "btn btn-primary "%>
    </div>
    <div class="col">
      <%= link_to "Back to posts", posts_path,class: "btn btn-secondary " %>
    </div>
    <div class="col">
      <%= button_to "Destroy this post", @post, method: :delete ,class: "btn btn-danger " %>
    </div>
  </div>
<hr/>
  <div >
    <%= @post.comments.count.to_s + " comment(s)"%>
    <hr/>
    <%= render @post.comments %>
    <h3>Leave a comment</h3>
    <br/>
    <%= render 'comments/form', comment: @comment%>
  </div>
</div>